name: Angular Test Coverage

on: [ push, pull_request ]

jobs:
  front-end-ci:
    name: Angular CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --browsers=ChromeHeadlessCI --watch=false

      - name: Run Build
        run: npm run build

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.FRONT_SONAR_TOKEN }}
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=ncazo
            -Dsonar.projectKey=ncazo_op-p10-front
            -Dsonar.sources=front/src
            -Dsonar.tests=front/src
            -Dsonar.typescript.lcov.reportPaths=front/coverage/bobapp/lcov-report/lcov.info
            -Dsonar.ts.tslintconfigpath=tslint.json
            -Dsonar.exclusions=front/**/node_modules/**,**/assets/**,**/*.spec.ts
            -Dsonar.test.inclusions=front/**/*.spec.ts
            -Dsonar.host.url=https://sonarcloud.io


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push Docker image (front)
        uses: docker/build-push-action@v4
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/op-10_front:latest